# Generated by Django 4.1 on 2022-09-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(related_name='label', to='notes.labels'),
        ),
    ]
