# Generated by Django 4.1 on 2022-09-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
